name: glide
description: GLIDE carpooling app
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_database: ^11.1.4
  google_maps_flutter: ^2.7.0
  flutter_dotenv: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
